### ISSUE TITLE
Идея для плагина

### ISSUE THREAD

**Issue by x1z53** [alt-gnome-team/App-Ideas#14]
Стоит разработать плагин, который будет добавлять функцию в контекстном меню для открытия папки из `Nautilus` в сторонних терминалах, к примеру `kitty`, аналогичную стандартной функции открытия в `GNOME Terminal`

**Comment by Rirusha** [comment]
Такое расшрение для Nautilus уже существует: https://github.com/Stunkymonkey/nautilus-open-any-terminal
