### ISSUE TITLE
Приложение для учёта бюджета

### ISSUE THREAD

**Issue by alexeev-engineer** [alt-gnome-team/App-Ideas#2]
Как все знают, рассчет бюджета помогает экономить и видеть траты. Такое приложение было бы очень полезно.

В нем должны быть функции:
 + Учет расходов и доходов
 + Сохранение в таблицы CSV/Excel
 + Графики трат и доходов
 + Типы доходов и расходов
 + Сохранение графиков

Приложение должно быть написано на GTK4

**Comment by Rirusha** [comment]
Чем лучше уже существующего положения? 

https://github.com/NickvisionApps/Denaro
