### ISSUE TITLE
Десктоп-клиент GitHub

### ISSUE THREAD

**Issue by alexeev-engineer** [alt-gnome-team/App-Ideas#5]
Создать десктоп клиент гитхаба.

Возможности:
 + Вход в аккаунт
 + Создание репозитория по https и ssh
 + Поддержка коммитов, push, pull request, веток, issue
 + Возможность создания репозитория в организации (в которой пользователь мембер)

**Comment by Rirusha** [comment]
Добавлю как идею: получение нотификаций из гитхаб (когда ишью появилось в репозитории, за которым следишь или GitHub action выдал failed...)

**Comment by Rirusha** [comment]
Так как есть Turtle, не вижу смысла в подобном приложении.
